feat: ユーザー情報入力画面の実装
kai-Bomb/iOSApp-StyleCast pull request #3
Opened 2024-12-12 13:08 UTC by kai-Bomb

## 詳細
ユーザーの基本情報を入力する画面を作成しました。

## スクリーンショット
<img src="https://github.com/user-attachments/assets/05636038-af35-42d5-bf98-d1ce907eae08" width=250>

2024-12-17 06:51 UTC, KyusokLee commented
レビューします！

2024-12-18 11:30 UTC, KyusokLee requested changes

2024-12-18 11:30 UTC, KyusokLee commented on StyleCast/Views/UserInfoInputViewController.swift
> +    private var viewModel = UserInfoInputViewModel()
ここは 変更を加えないので、let で良さそう！

2024-12-18 11:30 UTC, KyusokLee commented on StyleCast/Views/UserInfoInputViewController.swift
> +    private func setupActions() {
ここは、ボタンの定義時にaddTargetするのではなく、別途のメソッドとして分けた理由が知りたいかも！

2024-12-18 11:30 UTC, KyusokLee commented on StyleCast/Views/UserInfoInputViewController.swift
> +        maleButton.addTarget(self, action: #selector(selectMale), for: .touchUpInside)
[ここは変えても変えなくてもよし！]
`addAction`を使うと、objcのメソッドを作成しなくても済むので、全部swiftコードにしたいなら、おすすめ！
たとえば、こんな感じかな
```suggestion
        maleButton.addAction(.init { [weak self] _ in
            guard let self else { return }
            self.selectMale()
        }, for: .touchUpInside)
        ```
        func selectMale()
```

2024-12-18 11:30 UTC, KyusokLee commented on StyleCast/Views/UserInfoInputViewController.swift
> +        NotificationCenter.default.publisher(
ここを `NotificationCenter` にした理由が気になる！
`PassThroughSubject`利用も一つの方法かなと思っただけで、他に理由があるなら大丈夫です！
公式ドキュメント：https://developer.apple.com/documentation/combine/passthroughsubject

2024-12-19 02:28 UTC, cocona15531 approved these changes
LGTM！

2024-12-19 04:08 UTC, kai-Bomb commented on StyleCast/Views/UserInfoInputViewController.swift
> +    private var viewModel = UserInfoInputViewModel()
確かに！修正します！

2024-12-19 04:10 UTC, kai-Bomb commented on StyleCast/Views/UserInfoInputViewController.swift
> +    private func setupActions() {
個人的な好みで、アクションをまとめてるとみやすいかな？とか思っている。

ボタン定義のところでaddTargetする方が主流だったりするのかな？

2024-12-19 04:10 UTC, kai-Bomb commented on StyleCast/Views/UserInfoInputViewController.swift
> +        maleButton.addTarget(self, action: #selector(selectMale), for: .touchUpInside)
知らなかった！ありがとう！

2024-12-19 04:24 UTC, kai-Bomb commented on StyleCast/Views/UserInfoInputViewController.swift
> +        NotificationCenter.default.publisher(
Combineの知見がなくて実装方法を`NotificationCenter`で実装するしか知らなかった。
`PassThroughSubject`使った方がCombineっぽくて良さそうだね。

2024-12-26 08:54 UTC, kai-Bomb commented on StyleCast/Views/UserInfoInputViewController.swift
> +    private func setupActions() {
こんな感じ？
```
private lazy var maleButton: UIButton = {
        let button = UIButton()
        button.setTitle("", for: .normal)
        button.backgroundColor = UIColor.systemGray6
        button.layer.cornerRadius = 16
        button.layer.borderWidth = 2
        button.layer.borderColor = UIColor.clear.cgColor
        button.setImage(UIImage(systemName: "person.fill"), for: .normal)
        button.tintColor = .systemBlue
        button.translatesAutoresizingMaskIntoConstraints = false
        button.addTarget(self, action: #selector(selectMale), for: .touchUpInside)
        return button
}()
```

2024-12-26 09:39 UTC, kai-Bomb commented
@KyusokLee 
レビューありがとう！以下を修正しました！

- `var`を`let`に変更しました。
```
private let viewModel = UserInfoInputViewModel()
```


- `addTarget`を`addAction`に変更しました。
```
private func setupActions() {
        maleButton.addAction(.init { [weak self] _ in
            guard let self else { return }
            self.selectMale()
        }, for: .touchUpInside)
        femaleButton.addAction(.init { [weak self] _ in
            guard let self else { return }
            self.selectFemale()
        }, for: .touchUpInside)
        registerButton.addAction(.init { [weak self] _ in
            guard let self else { return }
            self.register()
        }, for: .touchUpInside)
}
```

2024-12-26 09:40 UTC, kai-Bomb commented on StyleCast/Views/UserInfoInputViewController.swift
> +        NotificationCenter.default.publisher(
現状こっちの方がシンプルかな？と思いました

2025-01-04 06:38 UTC, KyusokLee commented
@kai-Bomb 
修正ありがとう！！
確認できたので、Resolveするね！🫡

2025-01-04 06:38 UTC, KyusokLee commented on StyleCast/Views/UserInfoInputViewController.swift
> +    private func setupActions() {
@kai-Bomb 
確認遅くなった！🙏
なるほどね！

> addTargetする方が主流だったりするのかな

主流なのかはあんまり詳しくないけど、ただの好みだと思う！！なので、前のかっつんのコードでも良さそうな気がするよ！

なので、ここはResolve します！

2025-01-04 06:38 UTC, KyusokLee commented on StyleCast/Views/UserInfoInputViewController.swift
> +        NotificationCenter.default.publisher(
@kai-Bomb 
なるほどね！確かに簡単なやつなので、NotificationCenterのpublisherで良さそう！
ここもResolveするね！

2025-01-04 06:39 UTC, KyusokLee approved these changes

2025-01-04 06:42 UTC, KyusokLee commented
ここ、CoreData使用時に使いたいので、自分の方からmergeしちゃうね！！🙏

2025-01-04 06:42 UTC, merged